# name: HandleIssue

# on:
#     issues:
#         types:
#             - opened
#     workflow_dispatch:

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v3
#             - name: Set up Python 3.10
#               uses: actions/setup-python@v3
#               with:
#                   python-version: '3.10'

#             - name: Install dependencies
#               run: |
#                   python -m pip install --upgrade pip
#                   if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#             - name: StartTask
#               env:
#                   TOKEN: ${{ secrets.TOKEN }}
#               run: |
#                   # stop the build if there are Python syntax errors or undefined names
#                   python cli/issue.py
