name: Release
on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to run the workflow on'
                required: true
                default: 'template'

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set output
              id: vars
              run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

            # 安装 Node.js
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

    # 编译 Tauri
    build-app:
        needs: create-release
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: 'macos-latest'
                      target: 'aarch64-apple-darwin'
                    - platform: 'macos-latest'
                      target: 'x86_64-apple-darwin'

                    - platform: 'windows-latest'
                      target: 'x86_64-pc-windows-msvc'
                    - platform: 'windows-latest'
                      target: 'i686-pc-windows-msvc'
                    - platform: 'windows-latest'
                      target: 'aarch64-pc-windows-msvc'

                    - platform: 'ubuntu-22.04'
                      target: 'x86_64-unknown-linux-gnu'

        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - uses: pnpm/action-setup@v3
              with:
                  version: latest

            - name: Install rust target
              run: rustup target add ${{ matrix.target }}

            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

            # 安装 Rust
            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            # 使用 Rust 缓存，加快安装速度
            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: target

            # 获取 pnpm 缓存
            - name: Sync node version and setup cache
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            # 安装依赖, 前端打包
            - name: Install app dependencies and build web
              run: pnpm install

            # 执行构建，以及推送 github release
            - name: Build the app
              uses: tauri-apps/tauri-action@v0
              env:
                  CI: false
                  PLATFORM: ${{ matrix.platform }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: ${{ github.ref_name }}
                  releaseName: 'PakePlus v__VERSION__'
                  releaseBody: 'This is a workflow to help you automate the publishing of your PakePlus project to GitHub Packages.'
                  releaseDraft: true
                  prerelease: false
                  args: --target ${{ matrix.target }}
